Update Defaults
kivy/buildozer pull request #1512
Opened 2022-10-10 01:12 UTC by RobertFlatt

Update defaults to

android.api = 31
android.enable_androidx = True

2022-10-10 01:45 UTC, RobertFlatt commented
Are these fails an artifact of the test environment?

2022-10-15 08:19 UTC, misl6 commented
> Are these fails an artifact of the test environment?

iOS: 100%  an artifact
Android: `tests` need to be updated accordingly to your changes.

2022-10-15 08:20 UTC, misl6 requested changes
Can you please update the tests and ping me back when you're ready?

2022-10-17 02:16 UTC, RobertFlatt commented
@misl6  ping

2022-11-05 10:06 UTC, misl6 requested changes
Left a suggestion regarding `androidx`, let me know what you think about it 😃

2022-11-05 10:06 UTC, misl6 commented on buildozer/default.spec
> +android.enable_androidx = True
How about leaving the option commented (but with the updated default):
```suggestion
#android.enable_androidx = True
```

and having the default changed here?

https://github.com/kivy/buildozer/blob/b8575fd5b1e150bf93be3b7e77f229a28a7e5e0d/buildozer/targets/android.py#L1265-L1267

That will allow us to enable it by default, even for current users that may have an outdated `buildozer.spec`

2022-11-05 18:46 UTC, RobertFlatt commented
@misl6 Good idea, implemented.

2022-11-06 09:04 UTC, merged