Update Buildozer osx target to work with latest kivy 2.2.0
kivy/buildozer pull request #1614
Opened 2023-06-04 18:54 UTC by akshayaurora

2023-06-05 12:33 UTC, AndiEcker commented on buildozer/targets/osx.py
> +        return ['kivy', 'python3']
pyver = self.buildozer.config.get('app', 'osx.python_version')
        return ['kivy', f'python{pyver}']

2023-06-05 16:43 UTC, misl6 reviewed
Hi @akshayaurora !

I've left some comments, let me know your thoughts 😀

2023-06-06 16:28 UTC, misl6 requested changes

2023-06-06 16:28 UTC, misl6 commented on buildozer/targets/osx.py
> +        pyver = bcg('app', 'osx.python_version')
A PEP8 test is now failing here :)

2023-06-17 12:33 UTC, misl6 approved these changes
LGTM. Thank you!

2023-06-17 17:29 UTC, merged