For out logging code from Buildozer class
kivy/buildozer pull request #1632
Opened 2023-07-08 13:32 UTC by Julian-O

First step toward #1629.

Code related to logging moved into its own class/file.
References (including in targets and tests) updated.
Unit tests separated out, and enhanced to test more conditions.
Trivial indenting/grammar issues in osx.py fixed.
No-op exception handling code removed.

2023-07-08 16:25 UTC, Julian-O commented on buildozer/targets/osx.py
>              self.buildozer.info(
Missed this one.

2023-07-16 12:50 UTC, misl6 requested changes
Hi @Julian-O !

In `buildozer/scripts/remote.py` references have not been updated.
Can you please take care of it?

2023-07-17 19:49 UTC, misl6 requested changes
Seems we still have two old references:
https://github.com/kivy/buildozer/blob/0851a101b5e301803a42ed5f5562e6910bff116b/buildozer/scripts/client.py#L19
https://github.com/kivy/buildozer/blob/0851a101b5e301803a42ed5f5562e6910bff116b/buildozer/scripts/remote.py#L274

Unfortunately I missed them from the previous review.
(That part will likely need a huge cleanup, but makes sense to keep it updated ATM)

2023-07-18 14:05 UTC, Julian-O commented
These sneaky ones created a Buildozer() object just to call logging! I missed them in my text searches. That left me red-faced.  I should have caught these, sorry.

2023-07-20 20:05 UTC, misl6 approved these changes
LGTM. Thank you!

(The CI pipeline is failing, but is a known issue with Cython 3.0.0)

2023-07-20 20:05 UTC, merged