Migrate to use Buildop's rmtree, file_copy, file_copytree and rename
kivy/buildozer pull request #1669
Opened 2023-08-25 15:40 UTC by Julian-O

This is part of a bigger refactor to reduce the size and complexity of the Buildozer class. It adds no new functionality (apart from making logging more consistent)

* Remove file_rename, file_copy and file_copytree from Buildozer.
* Update all references to those Buildozer methods to refer to buildops equivalents.
   * Note: `file_rename` is now called rename as, in practice, it was also used to rename directories.
* Updated all references to shutil.copyfile and shutil.rmtree to use the Buildops equivalents
  * Note this adds implicit debug logging, making them more consistent.
* Updated all references to check_call() and check_output() that called the `rm` and `cp` shell commands.
  * Note this adds implicit debug logging, making them more consistent, and improves performance.
* Updated mock in test.

Cheekily, also removed some obsolete references to Python 2 (only) standard libraries to make my IDE stop warning me about them while I edited the file.

2023-08-25 15:50 UTC, misl6 requested changes
From a quick check, I've found (and added a comment) one reference of `file_rename` which needs to be migrated, can you take care of it?

2023-08-25 15:50 UTC, misl6 commented on buildozer/__init__.py
> -    def file_rename(self, source, target, cwd=None):
Seems we still have a reference to `file_rename` here:
https://github.com/kivy/buildozer/blob/b1f0e61ef30462df021f08ef1dc15bf10e40e8d6/buildozer/targets/ios.py#L313

2023-08-25 23:50 UTC, Julian-O commented
@misl6:

Good spot. I do remember seeing the log message directly above it ('Moving IPA to bin...' sounds like it is throwing away some beer) so I don't know how I missed this one. Fixed.

[I also accidentally gave a sneak preview of the *next* PR by committing in the wrong branch. I've undone that too.]

2023-08-26 07:41 UTC, misl6 commented
> ('Moving IPA to bin...' sounds like it is throwing away some beer)

😂

2023-08-26 07:57 UTC, misl6 approved these changes
LGTM. Thank you!

2023-08-26 07:57 UTC, merged